language: node_js
branches:
  except:master
node_js:
  - '0.12'
sudo: false
env:
  global:
    # Matthias token for Carrea/phosphor/website
    - secure: "hbwb8tDcMNqHy5VVfm/+BMrrTPsO5Xvc4jgFP9Qt4xP7jk4yP51uVCyjZ3Lml6P81bKB4LkFRwhYBcumuQYZI4AfJ6M5byH12EF5RwuZdMoybRKsk8npf6qZGbbn46df2burjSzM/DxoOp4XtpQM7TsOPHY2pCIJvV3gZ8zSxUY="
script:
  - if [[ $GROUP == docs ]]; then gulp examples; gulp docs; fi
  - git clone https://github.com/Carreau/phosphor-website.git build
  - cd build
  - git checkout -b gh-pages origin/gh-pages
  - cd ..
  - node index.js '/phosphor-website/'
  - cd build
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis Bot"
  - git add *
  - git commit -am'build docs'
after_success: |
  if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == 'master' ]]
  then
    pwd
    echo "Will push Documentation"
    git config credential.helper 'store --file=.git/credentials'
    git remote add ghpages https://github.com/carreau/phosphor-website.git
    echo "https://${GHTOKEN}:@github.com" > .git/credentials
    git push ghpages gh-pages:gh-pages
  else
    echo "Will only deploy docs build from master branch"
  fi

